version: '3.8'

services:
  neo4j-core-1:
    image: neo4j:5.0-enterprise
    container_name: neo4j-core-1
    hostname: neo4j-core-1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/riskradar2024
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Core server 설정
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=neo4j-core-1:5000,neo4j-core-2:5000,neo4j-core-3:5000
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j-core-1:7687
      - NEO4J_dbms_connector_http_advertised__address=neo4j-core-1:7474
      # 메모리 설정
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      # 백업 설정
      - NEO4J_dbms_backup_enabled=true
      - NEO4J_dbms_backup_address=0.0.0.0:6362
      # 모니터링
      - NEO4J_metrics_enabled=true
      - NEO4J_metrics_jmx_enabled=true
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2004
    volumes:
      - neo4j-core-1-data:/data
      - neo4j-core-1-logs:/logs
      - neo4j-core-1-conf:/conf
      - neo4j-core-1-plugins:/plugins
      - ./conf/neo4j.conf:/conf/neo4j.conf:ro
    networks:
      - neo4j-cluster
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G

  neo4j-core-2:
    image: neo4j:5.0-enterprise
    container_name: neo4j-core-2
    hostname: neo4j-core-2
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/riskradar2024
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Core server 설정
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=neo4j-core-1:5000,neo4j-core-2:5000,neo4j-core-3:5000
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j-core-2:7687
      - NEO4J_dbms_connector_http_advertised__address=neo4j-core-2:7474
      # 메모리 설정
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      # 백업 설정
      - NEO4J_dbms_backup_enabled=true
      - NEO4J_dbms_backup_address=0.0.0.0:6362
      # 모니터링
      - NEO4J_metrics_enabled=true
      - NEO4J_metrics_jmx_enabled=true
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2004
    volumes:
      - neo4j-core-2-data:/data
      - neo4j-core-2-logs:/logs
      - neo4j-core-2-conf:/conf
      - neo4j-core-2-plugins:/plugins
      - ./conf/neo4j.conf:/conf/neo4j.conf:ro
    networks:
      - neo4j-cluster
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    depends_on:
      - neo4j-core-1

  neo4j-core-3:
    image: neo4j:5.0-enterprise
    container_name: neo4j-core-3
    hostname: neo4j-core-3
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      - NEO4J_AUTH=neo4j/riskradar2024
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Core server 설정
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=neo4j-core-1:5000,neo4j-core-2:5000,neo4j-core-3:5000
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j-core-3:7687
      - NEO4J_dbms_connector_http_advertised__address=neo4j-core-3:7474
      # 메모리 설정
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      # 백업 설정
      - NEO4J_dbms_backup_enabled=true
      - NEO4J_dbms_backup_address=0.0.0.0:6362
      # 모니터링
      - NEO4J_metrics_enabled=true
      - NEO4J_metrics_jmx_enabled=true
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2004
    volumes:
      - neo4j-core-3-data:/data
      - neo4j-core-3-logs:/logs
      - neo4j-core-3-conf:/conf
      - neo4j-core-3-plugins:/plugins
      - ./conf/neo4j.conf:/conf/neo4j.conf:ro
    networks:
      - neo4j-cluster
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    depends_on:
      - neo4j-core-1

  # Read Replica for read scaling
  neo4j-replica-1:
    image: neo4j:5.0-enterprise
    container_name: neo4j-replica-1
    hostname: neo4j-replica-1
    ports:
      - "7477:7474"
      - "7690:7687"
    environment:
      - NEO4J_AUTH=neo4j/riskradar2024
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Read Replica 설정
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_causal__clustering_initial__discovery__members=neo4j-core-1:5000,neo4j-core-2:5000,neo4j-core-3:5000
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j-replica-1:7687
      - NEO4J_dbms_connector_http_advertised__address=neo4j-replica-1:7474
      # 메모리 설정 (읽기 전용이므로 약간 낮게)
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # 모니터링
      - NEO4J_metrics_enabled=true
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2004
    volumes:
      - neo4j-replica-1-data:/data
      - neo4j-replica-1-logs:/logs
      - neo4j-replica-1-conf:/conf
      - ./conf/neo4j.conf:/conf/neo4j.conf:ro
    networks:
      - neo4j-cluster
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
    depends_on:
      - neo4j-core-1
      - neo4j-core-2
      - neo4j-core-3

  # HAProxy for load balancing
  neo4j-proxy:
    image: haproxy:2.8
    container_name: neo4j-proxy
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - neo4j-cluster
    depends_on:
      - neo4j-core-1
      - neo4j-core-2
      - neo4j-core-3
      - neo4j-replica-1

volumes:
  neo4j-core-1-data:
  neo4j-core-1-logs:
  neo4j-core-1-conf:
  neo4j-core-1-plugins:
  neo4j-core-2-data:
  neo4j-core-2-logs:
  neo4j-core-2-conf:
  neo4j-core-2-plugins:
  neo4j-core-3-data:
  neo4j-core-3-logs:
  neo4j-core-3-conf:
  neo4j-core-3-plugins:
  neo4j-replica-1-data:
  neo4j-replica-1-logs:
  neo4j-replica-1-conf:

networks:
  neo4j-cluster:
    driver: bridge