version: '3.8'

services:
  graph-service:
    build: .
    container_name: graph-service
    ports:
      - "8003:8003"
    environment:
      - DOCKER_ENV=true
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOG_LEVEL=INFO
    depends_on:
      - neo4j
    networks:
      - riskradar_network

  neo4j:
    image: neo4j:5.0
    container_name: neo4j_graph_service
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_server_memory_heap_initial__size=1g
      - NEO4J_server_memory_heap_max__size=2g
      - NEO4J_server_memory_pagecache_size=1g
    volumes:
      - neo4j_data:/data
    networks:
      - riskradar_network

networks:
  riskradar_network:
    external: true

volumes:
  neo4j_data: